/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3diu.grupo41;

import java.io.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Entrar
 */
public class UmbralizadoImagen extends javax.swing.JFrame {

    /**
     * Creates new form UmbralizadoImagen
     */
    public UmbralizadoImagen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaAbrir = new javax.swing.JFileChooser();
        menuPadre = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemGuardar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuDialogo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menuPedir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setText("Archivo");

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAbrir.setText("Abrir");
        menuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemAbrir);

        menuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemGuardar.setText("Guardar");
        menuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemGuardar);

        menuPadre.add(menuArchivo);

        menuEditar.setText("Editar");
        menuPadre.add(menuEditar);

        menuDialogo.setText("Cuadro de Dialogo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuDialogo.add(menuSalir);

        menuPedir.setText("Pedir dato");
        menuPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedirActionPerformed(evt);
            }
        });
        menuDialogo.add(menuPedir);

        menuPadre.add(menuDialogo);

        setJMenuBar(menuPadre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);
        //ventanaAbrir.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            System.out.println("Fichero seleccionado: " + fc.getSelectedFile());
        }
    }//GEN-LAST:event_menuItemAbrirActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        int res = JOptionPane.showConfirmDialog(rootPane,
                "¿Estas seguro que quieres salir?",
                         "Salir",
                         JOptionPane.YES_NO_OPTION);
        if(res== JOptionPane.YES_OPTION){
            System.out.println("Terminar la aplicaciion");
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedirActionPerformed
        String res = (String) JOptionPane.showInputDialog(rootPane,
                "Introduzca nombre del gato",
                "Nombre gato",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null, //String[] combobox con las posibles opciones
                "Neko");
        System.out.println("Nombre del gato: " + res);
    }//GEN-LAST:event_menuPedirActionPerformed

    private void menuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGuardarActionPerformed
        JFileChooser fc = new JFileChooser(".");
        //Añadir filtros
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Ficheros xml","xml");
        fc.addChoosableFileFilter(filtro);
        
        
        int res = fc.showOpenDialog(null);
        //ventanaAbrir.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            System.out.println("Fichero seleccionado: " + fc.getSelectedFile());
        }
    }//GEN-LAST:event_menuItemGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UmbralizadoImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UmbralizadoImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UmbralizadoImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UmbralizadoImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UmbralizadoImagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuDialogo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemGuardar;
    private javax.swing.JMenuBar menuPadre;
    private javax.swing.JMenuItem menuPedir;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JFileChooser ventanaAbrir;
    // End of variables declaration//GEN-END:variables
}
